export default {
	animation: false,
	animationSteps: 60,
	animationEasing: "easeOutQuart",
	showScale: true,
	scaleOverride: false,
	scaleSteps: 40,
	scaleStepWidth: 50,
	scaleStartValue: -40,
	scaleLineColor: "rgba(0,0,0,.1)",
	scaleLineWidth: 1,
	scaleShowLabels: false,
	scaleLabel: "<%=value%>",
	scaleIntegersOnly: false,
	scaleBeginAtZero: false,
	scaleFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
	scaleFontSize: 12,
	scaleFontStyle: "normal",
	scaleFontColor: "#666",
	responsive: true,
	maintainAspectRatio: true,
	showTooltips: false,
	customTooltips: false,
	tooltipEvents: ["mousemove", "touchstart", "touchmove"],
	tooltipFillColor: "rgba(0,0,0,0.8)",
	tooltipFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
	tooltipFontSize: 14,
	tooltipFontStyle: "normal",
	tooltipFontColor: "#fff",
	tooltipTitleFontFamily: "'Helvetica Neue', 'Helvetica', 'Arial', sans-serif",
	tooltipTitleFontSize: 14,
	tooltipTitleFontStyle: "bold",
	tooltipTitleFontColor: "#fff",
	tooltipYPadding: 6,
	tooltipXPadding: 6,
	tooltipCaretSize: 8,
	tooltipCornerRadius: 6,
	tooltipXOffset: 10,
	tooltipTemplate: "<%if (label){%><%=label%>: <%}%><%= value %>",
	multiTooltipTemplate: "<%= value %>",
	scaleShowGridLines : true,
	scaleGridLineColor : "rgba(0,0,0,.05)",
	scaleGridLineWidth : 1,
	scaleShowHorizontalLines: true,
	scaleShowVerticalLines: false,
	bezierCurve : false,
	bezierCurveTension : 0.4,
	pointDot : false,
	pointDotRadius : 4,
	pointDotStrokeWidth : 1,
	pointHitDetectionRadius : 20,
	datasetStroke : true,
	datasetStrokeWidth : 2,
	datasetFill : false,
	legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",
	onAnimationProgress: function(){},
	onAnimationComplete: function(){}
};
